version: "3.9"

services:
  app:
    image: python:3.12-slim
    container_name: adc_contratos
    working_dir: /app
    volumes:
      - /home/contratos:app/contratos
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1 
    entrypoint: |
      /bin/bash -c "
      python -m venv /app/venv &&  # Crea un entorno virtual
      source /app/venv/bin/activate &&  # Activa el entorno virtual
      pip install --upgrade pip && # Actualiza pip
      pip install --no-cache-dir -r requirements.txt && # Instala las dependencias
      uvicorn main:app --host 0.0.0.0 --port 8001"  # Inicia la aplicación con uvicorn