name: App Authentication

on: [push]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Conexión al servidor por SSH
    - name: SSH into the server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Verificar si el contenedor 'adc_contratos' está corriendo y detenerlo si es necesario
          if docker ps -q -f name=adc_contratos; then
            echo "Deteniendo el contenedor adc_contratos..."
            docker stop adc_contratos
            docker rm adc_contratos
          fi

          # Verificar si el directorio /home/microservicio-contract/adc_contratos existe
          if [ -d "/home/microservicio-contract/adc_contratos" ]; then
            echo "Eliminando el repositorio existente..."
            rm -rf /home/microservicio-contract/adc_contratos
          fi

          # Clonar o actualizar el repositorio
          cd /home/microservicio-contract 
          git clone https://github.com/rafaeltolap/adc_contratos.git
          
          # Construir y levantar contenedor con Docker Compose
          cd /home/microservicio-contract/adc_contratos
          docker-compose up -d

          # Verificar si el contenedor se está ejecutando
          docker ps